/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  SubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as AyinTokenContractJson } from "../dex/ayin_token.ral.json";

// Custom types for the contract
export namespace AyinTokenTypes {
  export type Fields = {
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  AyinTokenInstance,
  AyinTokenTypes.Fields
> {
  at(address: string): AyinTokenInstance {
    return new AyinTokenInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<TestContractParams<AyinTokenTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getSymbol", params);
    },
    getName: async (
      params: Omit<TestContractParams<AyinTokenTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getName", params);
    },
    getDecimals: async (
      params: Omit<TestContractParams<AyinTokenTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: Omit<TestContractParams<AyinTokenTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getTotalSupply", params);
    },
  };
}

// Use this object to test and deploy the contract
export const AyinToken = new Factory(
  Contract.fromJson(
    AyinTokenContractJson,
    "",
    "81b5dad9ec529b4f2cbb9d7a6a3749f34ba25d839d22af2ea29e27c6ad0e0726"
  )
);

// Use this class to interact with the blockchain
export class AyinTokenInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<AyinTokenTypes.State> {
    return fetchContractState(AyinToken, this);
  }

  methods = {
    getSymbol: async (
      params?: AyinTokenTypes.CallMethodParams<"getSymbol">
    ): Promise<AyinTokenTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        AyinToken,
        this,
        "getSymbol",
        params === undefined ? {} : params
      );
    },
    getName: async (
      params?: AyinTokenTypes.CallMethodParams<"getName">
    ): Promise<AyinTokenTypes.CallMethodResult<"getName">> => {
      return callMethod(
        AyinToken,
        this,
        "getName",
        params === undefined ? {} : params
      );
    },
    getDecimals: async (
      params?: AyinTokenTypes.CallMethodParams<"getDecimals">
    ): Promise<AyinTokenTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        AyinToken,
        this,
        "getDecimals",
        params === undefined ? {} : params
      );
    },
    getTotalSupply: async (
      params?: AyinTokenTypes.CallMethodParams<"getTotalSupply">
    ): Promise<AyinTokenTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        AyinToken,
        this,
        "getTotalSupply",
        params === undefined ? {} : params
      );
    },
  };

  async multicall<Calls extends AyinTokenTypes.MultiCallParams>(
    calls: Calls
  ): Promise<AyinTokenTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      AyinToken,
      this,
      calls
    )) as AyinTokenTypes.MultiCallResults<Calls>;
  }
}
